# Generated by Django 4.0.5 on 2022-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semilleros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('facultad', models.CharField(max_length=250)),
                ('p_academico', models.CharField(max_length=250)),
                ('g_investigacion', models.CharField(max_length=250)),
                ('l_investigacion', models.CharField(max_length=250)),
                ('tematica_e_i', models.CharField(max_length=250)),
                ('justificacion', models.TextField()),
            ],
            options={
                'db_table': 'Semilleros',
            },
        ),
    ]
