# Generated by Django 4.0.5 on 2022-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_user_direccion_alter_user_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
